import { atom } from 'recoil';
import type { ProfileEntityType } from '@/types/entities/profileEntity';

export const profileState = atom<ProfileEntityType>({
  key: 'profile',
  default: {
    commedical_speciality: '',
    document_file_path: '',
    is_commedical: 0,
    document: null,
    last_name: '',
    first_name: '',
    last_name_hira: '',
    first_name_hira: '',
    birthday_year: 0,
    birthday_month: 0,
    birthday_day: 0,
    main_speciality: '',
    speciality_2: '',
    speciality_3: '',
    speciality_4: '',
    medical_specialities: [],
    qualification: '',
    expertise: '',
    confimation_type: '',
    qualified_year: 0,
    doctor_qualified_year: 0,
    doctor_qualified_month: 0,
    doctor_qualified_day: 0,
    doctor_number: '',
    tel: '',
    status: '',
    need_to_send_confimation: false,
    is_imperfect_profile: false,
    is_hospital_doctor: false,
    is_mail_notify: true,
    is_push_notify: false,
    not_seminar_mail_target: false,
    want_to_be_consultant: true,
    assignable: 0,
    graduation_year: null,
    use_prefecture: null,
    prefecture_code: '',
    hospital_id: '',
    hospital_name: '',
    graduated_university: '',
    is_invited: false,
    is_skip_confirmation_by_utm_source: false,
    questionary_selected_ids_csv: null,
    questionary_other: null,
  },
});
